AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket using CloudFormation

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket

Outputs:
  BucketName:
    Description: Name of the created bucket
    Value: !Ref DemoBucket
